//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.Item
{ 

public sealed partial class TbItems
{
    private readonly Dictionary<int, Item.ItemCfg> _dataMap;
    private readonly List<Item.ItemCfg> _dataList;
    
    public TbItems(JSONNode _json)
    {
        _dataMap = new Dictionary<int, Item.ItemCfg>();
        _dataList = new List<Item.ItemCfg>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = Item.ItemCfg.DeserializeItemCfg(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Item.ItemCfg> DataMap => _dataMap;
    public List<Item.ItemCfg> DataList => _dataList;

    public Item.ItemCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Item.ItemCfg Get(int key) => _dataMap[key];
    public Item.ItemCfg this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}