//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.Unit
{ 

public sealed partial class TbUnits
{
    private readonly Dictionary<int, Unit.TbUnitData> _dataMap;
    private readonly List<Unit.TbUnitData> _dataList;
    
    public TbUnits(JSONNode _json)
    {
        _dataMap = new Dictionary<int, Unit.TbUnitData>();
        _dataList = new List<Unit.TbUnitData>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = Unit.TbUnitData.DeserializeTbUnitData(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Unit.TbUnitData> DataMap => _dataMap;
    public List<Unit.TbUnitData> DataList => _dataList;

    public Unit.TbUnitData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Unit.TbUnitData Get(int key) => _dataMap[key];
    public Unit.TbUnitData this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}