//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;


namespace cfg
{ 
   
public sealed partial class Tables
{
    public Item.TbItems TbItems {get; }
    public Unit.TbUnits TbUnits {get; }
    public Map.TbMaps TbMaps {get; }
    public Skill.TbSkills TbSkills {get; }
    public Status.TbStatuses TbStatuses {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbItems = new Item.TbItems(loader("item_tbitems")); 
        tables.Add("Item.TbItems", TbItems);
        TbUnits = new Unit.TbUnits(loader("unit_tbunits")); 
        tables.Add("Unit.TbUnits", TbUnits);
        TbMaps = new Map.TbMaps(loader("map_tbmaps")); 
        tables.Add("Map.TbMaps", TbMaps);
        TbSkills = new Skill.TbSkills(loader("skill_tbskills")); 
        tables.Add("Skill.TbSkills", TbSkills);
        TbStatuses = new Status.TbStatuses(loader("status_tbstatuses")); 
        tables.Add("Status.TbStatuses", TbStatuses);
        PostInit();

        TbItems.Resolve(tables); 
        TbUnits.Resolve(tables); 
        TbMaps.Resolve(tables); 
        TbSkills.Resolve(tables); 
        TbStatuses.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbItems.TranslateText(translator); 
        TbUnits.TranslateText(translator); 
        TbMaps.TranslateText(translator); 
        TbSkills.TranslateText(translator); 
        TbStatuses.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}