//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.Skill
{ 

public sealed partial class SkillCfg :  Bright.Config.BeanBase 
{
    public SkillCfg(JSONNode _json) 
    {
        { if(!_json["Id"].IsNumber) { throw new SerializationException(); }  Id = _json["Id"]; }
        { if(!_json["Name"].IsString) { throw new SerializationException(); }  Name = _json["Name"]; }
        { if(!_json["Type"].IsString) { throw new SerializationException(); }  Type = _json["Type"]; }
        { if(!_json["TargetGroup"].IsString) { throw new SerializationException(); }  TargetGroup = _json["TargetGroup"]; }
        { if(!_json["TargetSelect"].IsString) { throw new SerializationException(); }  TargetSelect = _json["TargetSelect"]; }
        { if(!_json["Cooldown"].IsNumber) { throw new SerializationException(); }  Cooldown = _json["Cooldown"]; }
        { if(!_json["Description"].IsString) { throw new SerializationException(); }  Description = _json["Description"]; }
        PostInit();
    }

    public SkillCfg(int Id, string Name, string Type, string TargetGroup, string TargetSelect, float Cooldown, string Description ) 
    {
        this.Id = Id;
        this.Name = Name;
        this.Type = Type;
        this.TargetGroup = TargetGroup;
        this.TargetSelect = TargetSelect;
        this.Cooldown = Cooldown;
        this.Description = Description;
        PostInit();
    }

    public static SkillCfg DeserializeSkillCfg(JSONNode _json)
    {
        return new Skill.SkillCfg(_json);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 技能类型
    /// </summary>
    public string Type { get; private set; }
    /// <summary>
    /// 目标阵营类型
    /// </summary>
    public string TargetGroup { get; private set; }
    /// <summary>
    /// 目标选择类型
    /// </summary>
    public string TargetSelect { get; private set; }
    /// <summary>
    /// 冷却时间
    /// </summary>
    public float Cooldown { get; private set; }
    /// <summary>
    /// 技能描述
    /// </summary>
    public string Description { get; private set; }

    public const int __ID__ = 450442128;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "TargetGroup:" + TargetGroup + ","
        + "TargetSelect:" + TargetSelect + ","
        + "Cooldown:" + Cooldown + ","
        + "Description:" + Description + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
