//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Text.Json;



namespace cfg.Map
{


public sealed partial class TbMaps
{
    private readonly Dictionary<int, Map.MapCfg> _dataMap;
    private readonly List<Map.MapCfg> _dataList;
    
    public TbMaps(JsonElement _json)
    {
        _dataMap = new Dictionary<int, Map.MapCfg>();
        _dataList = new List<Map.MapCfg>();
        
        foreach(JsonElement _row in _json.EnumerateArray())
        {
            var _v = Map.MapCfg.DeserializeMapCfg(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Map.MapCfg> DataMap => _dataMap;
    public List<Map.MapCfg> DataList => _dataList;

    public Map.MapCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Map.MapCfg Get(int key) => _dataMap[key];
    public Map.MapCfg this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    

    partial void PostInit();
    partial void PostResolve();
}

}