//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Text.Json;



namespace cfg.Skill
{

public sealed partial class SkillCfg :  Bright.Config.BeanBase 
{
    public SkillCfg(JsonElement _json) 
    {
        Id = _json.GetProperty("Id").GetInt32();
        Name = _json.GetProperty("Name").GetString();
        Type = _json.GetProperty("Type").GetString();
        TargetGroup = _json.GetProperty("TargetGroup").GetString();
        TargetSelect = _json.GetProperty("TargetSelect").GetString();
        Cooldown = _json.GetProperty("Cooldown").GetSingle();
        Description = _json.GetProperty("Description").GetString();
        PostInit();
    }

    public SkillCfg(int Id, string Name, string Type, string TargetGroup, string TargetSelect, float Cooldown, string Description ) 
    {
        this.Id = Id;
        this.Name = Name;
        this.Type = Type;
        this.TargetGroup = TargetGroup;
        this.TargetSelect = TargetSelect;
        this.Cooldown = Cooldown;
        this.Description = Description;
        PostInit();
    }

    public static SkillCfg DeserializeSkillCfg(JsonElement _json)
    {
        return new Skill.SkillCfg(_json);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 技能类型
    /// </summary>
    public string Type { get; private set; }
    /// <summary>
    /// 目标阵营类型
    /// </summary>
    public string TargetGroup { get; private set; }
    /// <summary>
    /// 目标选择类型
    /// </summary>
    public string TargetSelect { get; private set; }
    /// <summary>
    /// 冷却时间
    /// </summary>
    public float Cooldown { get; private set; }
    /// <summary>
    /// 技能描述
    /// </summary>
    public string Description { get; private set; }

    public const int __ID__ = 450442128;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "TargetGroup:" + TargetGroup + ","
        + "TargetSelect:" + TargetSelect + ","
        + "Cooldown:" + Cooldown + ","
        + "Description:" + Description + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}
