//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Text.Json;



namespace cfg.Skill
{


public sealed partial class TbSkills
{
    private readonly Dictionary<int, Skill.SkillCfg> _dataMap;
    private readonly List<Skill.SkillCfg> _dataList;
    
    public TbSkills(JsonElement _json)
    {
        _dataMap = new Dictionary<int, Skill.SkillCfg>();
        _dataList = new List<Skill.SkillCfg>();
        
        foreach(JsonElement _row in _json.EnumerateArray())
        {
            var _v = Skill.SkillCfg.DeserializeSkillCfg(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Skill.SkillCfg> DataMap => _dataMap;
    public List<Skill.SkillCfg> DataList => _dataList;

    public Skill.SkillCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Skill.SkillCfg Get(int key) => _dataMap[key];
    public Skill.SkillCfg this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    

    partial void PostInit();
    partial void PostResolve();
}

}