//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.Status
{ 

public sealed partial class StatusCfg :  Bright.Config.BeanBase 
{
    public StatusCfg(JSONNode _json) 
    {
        { if(!_json["Id"].IsNumber) { throw new SerializationException(); }  Id = _json["Id"]; }
        { if(!_json["ID"].IsString) { throw new SerializationException(); }  ID = _json["ID"]; }
        { if(!_json["Name"].IsString) { throw new SerializationException(); }  Name = _json["Name"]; }
        { if(!_json["Type"].IsString) { throw new SerializationException(); }  Type = _json["Type"]; }
        { if(!_json["StatusSlot"].IsString) { throw new SerializationException(); }  StatusSlot = _json["StatusSlot"]; }
        { if(!_json["CanStack"].IsString) { throw new SerializationException(); }  CanStack = _json["CanStack"]; }
        { if(!_json["Description"].IsString) { throw new SerializationException(); }  Description = _json["Description"]; }
        PostInit();
    }

    public StatusCfg(int Id, string ID, string Name, string Type, string StatusSlot, string CanStack, string Description ) 
    {
        this.Id = Id;
        this.ID = ID;
        this.Name = Name;
        this.Type = Type;
        this.StatusSlot = StatusSlot;
        this.CanStack = CanStack;
        this.Description = Description;
        PostInit();
    }

    public static StatusCfg DeserializeStatusCfg(JSONNode _json)
    {
        return new Status.StatusCfg(_json);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 状态ID
    /// </summary>
    public string ID { get; private set; }
    /// <summary>
    /// 状态名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 状态类型
    /// </summary>
    public string Type { get; private set; }
    /// <summary>
    /// 显示在状态栏
    /// </summary>
    public string StatusSlot { get; private set; }
    /// <summary>
    /// 能否叠加
    /// </summary>
    public string CanStack { get; private set; }
    /// <summary>
    /// 状态描述
    /// </summary>
    public string Description { get; private set; }

    public const int __ID__ = -901014506;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "StatusSlot:" + StatusSlot + ","
        + "CanStack:" + CanStack + ","
        + "Description:" + Description + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
