//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Text.Json;

namespace cfg
{ 

   
public sealed partial class Tables
{
    public Item.TbItems TbItems {get; }
    public Unit.TbUnits TbUnits {get; }

    public Tables(System.Func<string, JsonElement> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbItems = new Item.TbItems(loader("item_tbitems")); 
        tables.Add("Item.TbItems", TbItems);
        TbUnits = new Unit.TbUnits(loader("unit_tbunits")); 
        tables.Add("Unit.TbUnits", TbUnits);
        PostInit();

        TbItems.Resolve(tables); 
        TbUnits.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbItems.TranslateText(translator); 
        TbUnits.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
