//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Text.Json;



namespace cfg.Map
{

public sealed partial class MapCfg :  Bright.Config.BeanBase 
{
    public MapCfg(JsonElement _json) 
    {
        Id = _json.GetProperty("id").GetInt32();
        Name = _json.GetProperty("name").GetString();
        Type = _json.GetProperty("type").GetString();
        IsCopyMap = _json.GetProperty("isCopyMap").GetInt32();
        Desc = _json.GetProperty("desc").GetString();
        PostInit();
    }

    public MapCfg(int id, string name, string type, int isCopyMap, string desc ) 
    {
        this.Id = id;
        this.Name = name;
        this.Type = type;
        this.IsCopyMap = isCopyMap;
        this.Desc = desc;
        PostInit();
    }

    public static MapCfg DeserializeMapCfg(JsonElement _json)
    {
        return new Map.MapCfg(_json);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public string Type { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public int IsCopyMap { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }

    public const int __ID__ = 618094202;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "IsCopyMap:" + IsCopyMap + ","
        + "Desc:" + Desc + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}
